config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'tweets/search'

   root 'users#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :mentions, class_name: 'User', join_table: 'mentions'

  after_create :build_mentions

  def remote_id
    source["id"]
  end

  def self.search_text query
    where("to_tsvector('english', text) @@ to_tsquery(?)", parse_query( query ) )
  end

  def username
    user.name
  end

  private
  def self.parse_query query
    query.to_s.gsub(/[^a-zA-Z0-9]/, ' ').split(' ').join(' & ')
  end

  def build_mentions
    mentions << local_mentions
  end

  def remote_mentions
    source.nil? ? [] : source["entities"]["user_mentions"].map{|m| m["screen_name"]}
  end

  def local_mentions
    remote_mentions.map{|m| User.find_by( name: m )}.compact
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets, dependent: :destroy
  has_and_belongs_to_many :mentions, class_name: 'Tweet', join_table: 'mentions'

  def self.update_tweets
    all.each(&:update_tweets)
  end

  def self.update_mentions_count
    all.map(&:update_mentions_count)
  end

  def mentions_count_cache
    count_of_mentions || update_mentions_count()
  end

  def update_tweets
    TweetsStorer.new( self, { text: :text,
                             retweets: :retweet_count,
                             favourites: :favorite_count,
                             source: :to_json })
                .store( fetch_tweets )
  end

  def fetch_tweets
    tc = TweetsCatcher.new
    if tweets.empty?
      tc.fetch_all_user_tweets self.name
    else
      tc.fetch_latest_tweets self.name, latest_fetched_tweet_id
    end
  end

  def update_mentions_count
    update_attribute( :count_of_mentions, mentions.count)
    count_of_mentions
  end

  private
  def latest_fetched_tweet_id
    tweets.first.remote_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def search
    @result = sort( Tweet.search_text( search_query ) )

    respond_to do |format|
      format.html{ render :search }
      format.json{ paginate json: @result }
    end
  end

  private
  def search_query
    params[:q]
  end

  def sort result
    sort_options[sort_type].call( result )
  end

  def sort_type
    params[:sort]
  end

  def sort_options
    {
      "favourites" => ->( result ){ result.order( favourites: :desc ) },
      "retweets" => ->( result ){  result.order( retweets: :desc )  }
    }.tap{ |hsh|
      hsh.default = ->( result ){  result.order( retweets: :desc, favourites: :desc )  }
    }
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.order( :count_of_mentions )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order( count_of_mentions: :desc )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="tweetRank">
<head>
  <title>AngularTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_search.html.erb
<%= form_tag('/tweets/search', method: :get) do %> 
  <%= label_tag( :q, "Search tweets text" ) %>
  <%= text_field_tag( :q, params[:q], placeholder: 'Enter search term..'  ) %>
  <%= label_tag( :sort_retweet, "Sort by retweets" ) %>
  <%= radio_button_tag( :sort, 'retweets', true) %>
  <%= label_tag( :sort_favorites, "Sort by favorites" ) %>
  <%= radio_button_tag( :sort, 'favourites') %>
  <%= submit_tag( "Search" ) %>
<% end %>

app/views/tweets/search.html.erb
<%= link_to( "Go to user list", users_index_path ) %>

<div ng-controller='TweetsPaginationCtrl'>
  <h1>Tweets search: {{tweets.query}} sort: {{sort}}</h1>
  <form>
    <input type="text" ng-model="tweetsSearchText" value="{{tweets.query}}" ng-model-instant>
    <input type="radio" ng-model="sort" value="retweets">  Sort by Retweets <br/>
    <input type="radio" ng-model="sort" value="favourites">  Sort by Favourites <br/>
    <button ng-click="tweetsSearch()" > Search! </button>
  </form>

  <div infinite-scroll='tweets.nextPage()' infinite-scroll-disabled='tweets.busy || tweets.done' infinite-scroll-distance='1'>
    <div ng-repeat='item in tweets.items track by $index'>
      <span>{{item.text}} | rt: {{item.retweets}} | fv: {{item.favourites}}</span>
    </div>
    <div ng-show='tweets.busy'>Loading data...</div>
    <div ng-show='tweets.done'>Fetched all!</div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'tweets/search' %>

<h1>List of users ranked by number of mentions</h1>

<div ng-controller="MainCtrl">
  <nvd3 options="options" data="data"></nvd3>
</div>